ouyou3-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
  resource :favorites, only: [:create, :destroy]
  end
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :users, only: [:show, :create, :index, :destroy, :edit, :update]
  resources :book, only: [:new, :create, :index, :show, :destroy] do
  resources :book_comments, only: [:create, :destroy]
  end
end

ouyou3-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ouyou3-master/app/models/book.rb
class Book < ApplicationRecord
   belongs_to :user
   validates :title, presence: true
   validates :body, presence: true
   validates :body, length: { maximum: 200 }
   has_many :favorites, dependent: :destroy
   has_many :book_comments, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

ouyou3-master/app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

ouyou3-master/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

ouyou3-master/app/models/hoge.rb
class Hoge < ApplicationRecord
end

ouyou3-master/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }


end

ouyou3-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
     user_path(current_user.id)
    end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

ouyou3-master/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  	def create
		@book = Book.find(params[:book_id])
		@book_comment = BookComment.new(book_comment_params)
		@book_comment.book_id = @book.id
		@book_comment.user_id = current_user.id
		if @book_comment.save
  		redirect_to book_path(@book.id)
		else
		  render 'books/show'
		end
	end

	def destroy
		@book = Book.find(params[:book_id])
  	book_comment = @book.book_comments.find(params[:id])
		book_comment.destroy
		redirect_to request.referer
	end

	private
	def book_comment_params
		params.require(:book_comment).permit(:comment)
	end
end

ouyou3-master/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  # 投稿データの保存
  def create
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    #@user= user.find(params[:id])
    if @book.save
       flash[:notice] = "You have created book successfully."
       redirect_to book_path(@book)
    else
     @user = current_user
     @books = Book.all
      render:index
    end
  end

def edit
 @book = Book.find(params[:id])
  if @book.user == current_user
   render "edit"
  else
   redirect_to books_path
  end
end

  def index
    @book = Book.new
    @user = current_user
    @books = Book.all
  end

  def show
    #book =book.update(book_params)
    #book.save
    #redirect_to '/top'
    @book = Book.find(params[:id])
    @book_new = Book.new
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
    #@username = User.find(session[:user_id])
  end

   #private
  # ストロングパラメータ
  #def book_params
   # params.require(:list).permit(:title, :body)
  #end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
        flash[:notice] = "You have created book successfully."
        redirect_to book_path(@book)
    else
      render:edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

   # 投稿データのストロングパラメータ
  private
  def book_params
    params.require(:book).permit(:title, :body)#.merge(user_id: current_user.id)
  end

end

ouyou3-master/app/controllers/concerns/book_comments_controller.rb
class BookCommentsController < ApplicationController

def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    @book_comment.save
    redirect_to book_path(@book)
end

def destroy
end


private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

ouyou3-master/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = book.favorites.new(user_id:current_user.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = book.favorites.find_by(user_id:current_user.id)
    favorite.destroy
    redirect_to request.referer
  end

end

ouyou3-master/app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
end

ouyou3-master/app/controllers/users_controller.rb
class UsersController < ApplicationController
 def show
  @user = User.find(params[:id])
  # @book = @user.book.page(params[:page]).reverse_order
  @book = Book.new
  @books = @user.books
 end

 def index
  @user = current_user
  @booknew = Book.new
  @users = User.all
  @book_favorites = current_user
 end

 def edit
  @user = User.find(params[:id])
   if @user.id == current_user.id
    render :edit
   else
    redirect_to user_path(current_user.id)
   end
 end

 def update
     @user = User.find(params[:id])
   if @user.update(user_params)
         flash[:notice] = "You have created book successfully."
         redirect_to user_path(@user)
   else
       render:edit
   end
 end

  def change
  add_index :users, :email, unique: true
  end

   private
   # ストロングパラメータ
   def user_params
     params.require(:user).permit(:name,:introduction,:profile_image)
   end

end

ouyou3-master/app/helpers/application_helper.rb
module ApplicationHelper
end

ouyou3-master/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

ouyou3-master/app/helpers/homes_helper.rb
module HomesHelper
end

ouyou3-master/app/helpers/post_images_helper.rb
module PostImagesHelper
end

ouyou3-master/app/helpers/users_helper.rb
module UsersHelper
end

ouyou3-master/app/views/books/edit.html.erb
<main>
   <div class="container">
   <div class="row">
   <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
       <% if @book.errors.any? %>
       <%= @book.errors.count %>errors prohibited this obj from being saved:
       <% @book.errors.full_messages.each do |message| %>
       <%= message %>
       <% end %>
       <% end %>
<h2>Editing Book</h2>

    <%= form_with model: @book, local:true do |f| %>
    <p>Title</p>
     <%= f.text_field :title %>
    <p>Opinion</p>
     <%= f.text_area :body %>
    <div class="form-group">
     <tb><%= f.submit "Update Book", class: "btn btn-success" %></tb>
     <% end %>
     <th></th>
     <tb><%= link_to "Show", book_path(@book) %>|<%= link_to "Back", books_path %></tb>

    </div>
  </div>
</main>

ouyou3-master/app/views/books/index.html.erb
  <main>
  <div class="container">
   <div class="row">
   <div class="col-md-3 ">
       <% if @book.errors.any? %>
       <%= @book.errors.count %>errors prohibited this obj from being saved:
       <% @book.errors.full_messages.each do |message| %>
       <%= message %>
       <% end %>
       <% end %>
    <h1>User info</h1>
    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
<table class="table">
  <tbody>
<tr></tr>
  <tr>
 <th>name</th>
 <th><%= @user.name %></th>
  </tr>
  <tr>
 <th>introduction</th>
 <th><%= @user.introduction %></th>
  </tr>
</tbody></table>


     <%= link_to edit_user_path(@user.id) do %>
      <i class="fas fa-user-cog" ></i>
     <% end %>

    <h2>New book</h2>
    <%= form_with model: @book, local:true do |f| %>
    <p>Title</p>
     <%= f.text_field :title %>
    <p>Opinion</p>
     <%= f.text_area :body %>
    <div class="form-group">
     <%= f.submit "Create Book", class: "btn btn-success" %>
     <% end %>
    </div>
  </div>

     <div class="col-md-8 offset-md-1">
       <h2>Books</h2>
       <table class="table table-hover table-inverse">
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <% @books.each do |book| %>
          <tr>
          <td>
           <%= link_to user_path(book.user.id) do %>
           <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40 ,size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
           <% end %>
           </td>

          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
          <td>
          <% if book.favorited_by?(current_user) %>
         <%= link_to book_favorites_path(book), method: :delete do %>
         ♥<%= book.favorites.count %>
         <% end %>

         <% else %>

         <%= link_to book_favorites_path(book), method: :post do %>
         ♡<%= book.favorites.count %>
         <% end %>
          <p>コメント件数：<%= book.book_comments.count %></p>
         <% end %></td>
<% end %>
       </table>
      </div>
     </div>
    </div>
   </main>

ouyou3-master/app/views/books/new.html.erb
  <main>
  <div class="container">
   <div class="row">
   <div class="col-md-3 ">
       <% if @book.errors.any? %>
       <%= @book.errors.count %>errors prohibited this obj from being saved:
       <% @book.errors.full_messages.each do |message| %>
       <%= message %>
       <% end %>
       <% end %>
    <h1>User info</h1>
    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
<table class="table">
  <tbody>
<tr></tr>
  <tr>
 <th>name</th>
 <th><%= @user.name %></th>
  </tr>
  <tr>
 <th>introduction</th>
 <th><%= @user.introduction %></th>
  </tr>
</tbody></table>


     <%= link_to edit_user_path(@user.id) do %>
      <i class="fas fa-user-cog" ></i>
     <% end %>

    <h2>New book</h2>
    <%= form_with model: @book, local:true do |f| %>
    <p>Title</p>
     <%= f.text_field :title %>
    <p>Opinion</p>
     <%= f.text_area :Opinion %>
    <div class="form-group">
     <%= f.submit "Create Book", class: "btn btn-success" %>
     <% end %>
    </div>
  </div>

     <div class="col-md-8 offset-md-1">
       <h2>Books</h2>
       <table class="table table-hover table-inverse">
         <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
         </tr>
         <tr>
              <% @book.each do |book| %>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>
          <% end %>
          </tr>
       </table>
      </div>
     </div>
    </div>
   </main>

ouyou3-master/app/views/books/show.html.erb
<main>

 <div class="container">
  <div class="row">
  <div class="col-md-3">
        <% if @book.errors.any? %>
       <%= @book.errors.count %>errors prohibited this obj from being saved:
       <% @book.errors.full_messages.each do |message| %>
       <%= message %>
       <% end %>
       <% end %>
   <h2>User info</h2>
   <table>
    <thead>
     <tbody>
      <%= attachment_image_tag @users, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
      <tr></tr>
        <tr>
       <th>name</th>
       <%= @book.book_comments %>
        </tr>
        <tr>
       <th>introduction</th>
       <%= @book.book_comments %>
        </tr>
      </tbody></table>

       <%= link_to  edit_book_path(@book) do %>
      <i class="fas fa-user-cog" ></i>
     <% end %>



   <h2>New book</h2>
   <%= form_with model: @booknew, local:true do |f| %>
   <p>Title</p>
    <%= f.text_field :title %>
   <p>Opinion</p>
    <%= f.text_area :body %>
   <div class="form-group">
    <%= f.submit "Create Book", class: "btn btn-success" %>
    <% end %>
   </div>
   </div>

     <div class="col-md-8 offset-md-1">
       <h2>Book  detail</h2>
       <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
         <tbody>
          <td></td>
           <td><%= link_to user_path(@book.user) do %>
           <%= attachment_image_tag @users, :profile_image, size: "40x40", fallback:"no_image.jpg" %>
           <% end %></td>
           <td><%= link_to user_path(@book.user) %></td>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>
         <% if @book.user.id == current_user.id %>
           <div class="form-group">
           <td><%= link_to  'Edit', edit_book_path(@book), class:"btn btn-sm btn-success" %></td>
           <td><%= link_to 'Destroy', book_path(@book), method: :delete,  class:"btn btn-sm btn-danger" %></td>
         <% end %>

         #コメント
          <% @book_comments.each do |book_comment| %>
            <p><%= attachment_image_tag('sample-author1.jpg') %></p>
            <%= book_comment.user.name %>
            <%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.count %>
          <% end %>
          </div>
           <p><%= link_to "{book_comments.count} コメント", book %>
          <div class="new-comment">
          <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
            <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
            <%= f.submit "送信する" %>
          <% end %>
</div>

         </tr>
          </tbody>
         </tr>
       </table>
      </div>
  </div>
  </div>
</main>

ouyou3-master/app/views/homes/about.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        </div>
    </div>
  </div>
</main>

ouyou3-master/app/views/homes/top.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
           <div class="row">
            <% if user_signed_in? %>
             <%= link_to 'Log in', books_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
          </div>
          <div class="row">
            <%= link_to 'Sign Up', books_path, class: "btn btn-success btn-sm btn-block sign_up" %>
          </div>
          <% else %>
          <div class="row">
             <%= link_to 'Log in', new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
          </div>
          <div class="row">
            <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

ouyou3-master/app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <%= link_to "Home", user_path(current_user), class:"fas fa-home nav-link text-light" %>
          <%= link_to "Users",users_path, class:"fas fa-users nav-link text-light" %>
           <%= link_to "Books", books_path, class:"fas fa-book-open nav-link text-light" %>
           <%= link_to "logout", destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt  nav-link text-light" %>
          <% else %>
            <%= link_to "Home", root_path, class:"fas fa-home nav-link text-light" %>
            <%= link_to "About", home_about_path, class:"fas fa-link nav-link text-light"  %>
            <%= link_to "sign up",new_user_registration_path, class:"fas fa-user-plus nav-link text-light" %>
            <%= link_to "login", new_user_session_path, class:"fas fa-sign-in-alt nav-link text-light" %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
    <br></br>
    <main>
      <p class="notice"><%= notice %>

        <p class="alert"><%= alert %>
    <%= yield %>
    </main>
     <center>
    <p>CopyRight Infratop.inc</p>
     </center>
    <% if user_signed_in? %>

      <li>

      </li>
    <% end %>

  </body>



</html>

ouyou3-master/app/views/users/edit.html.erb
  <div class="container">
    <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h2>User info</h2>
       <% if @user.errors.any? %>
       <%= @user.errors.count %>errors prohibited this obj from being saved:
       <% @user.errors.full_messages.each do |message| %>
       <%= message %>
       <% end %>
       <% end %>
         <p>name</p>
         <%= form_with model: @user, local:true do |f| %>
          <%= f.text_field :name %>
           <p>Image</p>
            <%= f.attachment_field :profile_image %>
           <p>Introduction</p>
            <%=f.text_area :introduction %>
            <%= f.submit "Update User", class: "btn btn-secondary" %>
            <% end %>
    </div>
   </div>
  </div>

ouyou3-master/app/views/users/index.html.erb
<main>
 <div class="container">
  <div class="row">
  <div class="col-md-3 ">
   <h2>User info</h2>
   <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
 <table class="table">
  <tbody>
<tr></tr>
  <tr>
 <th>name</th>
  <td><%= @user.name %></td>
  </tr>
  <tr>
 <th>introduction</th>
 <td><%= @user.introduction %></td>
  </tr>
</tbody>
</table>
     <%= link_to edit_user_path(@user.id) do %>
      <i class="fas fa-user-cog" ></i>
     <% end %>

   <h2>New book</h2>
   <%= form_with model: @booknew, local:true do |f| %>
   <p>Title</p>
    <%= f.text_field :title %>
   <p>Opinion</p>
    <%= f.text_area :body %>
   <div class="form-group">
    <%= f.submit "Create Book", class: "btn btn-success" %>
    <% end %>
   </div>
   </div>

     <div class="col-md-8 offset-md-1">
       <h2>Users</h2>
       <table class="table table-hover table-inverse">

         <tr>
          <th></th>
          <th>image</th>
          <th>name</th>
         </tr>
          <% @users.each do |user| %>
         <tr>
           <td><%= attachment_image_tag user, :profile_image, size: "40x40", fallback:"no_image.jpg" %></td>
           <td><%= user.name %></td>
           <td><%= link_to "Show", user_path(user) %></td>
         </tr>
         <% end %>

       </table>
      </div>
      </div>
  </div>
</main>

ouyou3-master/app/views/users/show.html.erb
<main>
 <div class="container">
 <div class="row">
 <div class="col-md-3 ">
       <% if @book.errors.any? %>
       <%= @book.errors.count %>errors prohibited this obj from being saved:
       <% @book.errors.full_messages.each do |message| %>
       <%= message %>
       <% end %>
       <% end %>
  <h1>User info</h1>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
  <table class="table">
  <tbody>
<tr></tr>
  <tr>
 <th>name</th>
 <td><%= @user.name %></td>
  </tr>
  <tr>
 <th>introduction</th>
 <th><%= @user.introduction %></th>
  </tr>
</tbody></table>

       <%= link_to edit_user_path(@user.id) do %>
      <i class="fas fa-user-cog" ></i>
     <% end %>
  <h2>New book</h2>
  <%= form_with model: @book, local:true do |f| %>
  <p>Title</p>
   <%= f.text_field :title %>
  <p>Opinion</p>
   <%= f.text_area :body %>
  <div class="form-group">
   <%= f.submit "Create Book", class: "btn btn-success" %>
   <% end %>
  </div>


   </div>
   <div class="col-md-8 offset-md-1">
       <h2>Books </h2>
       <table class="table table-hover table-inverse">
         <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          </tr>
           <% @books.each do |book| %>
           <tr>
           <td></td>
           <td><%= link_to user_path(book.user) do %>
               <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback:"no_image.jpg" %>
               <% end %>
            </td>
          <td><%= link_to book.title, book_path(book) %></td>
          <td><%= book.body %></td>
          </tr>
          <% end %>
       </table>
      </div>
  </div>
 </div>
 </main>