config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
  resources :book_comments, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
  end
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :users, only: [:show, :create, :index, :destroy, :edit, :update]


end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
<<<<<<< HEAD

=======
  
>>>>>>> 8c9886d0fc2ff2c2a3b1084824cc18a5a29ebe2f
  	def create
		@book = Book.find(params[:book_id])
		@book_comment = BookComment.new(book_comment_params)
		@book_comment.book_id = @book.id
		@book_comment.user_id = current_user.id
		if @book_comment.save
  		redirect_to book_path(@book.id)
		else
		  render 'books/show'
		end
	end

	def destroy
		@book = Book.find(params[:book_id])
  	book_comment = @book.book_comments.find(params[:id])
		book_comment.destroy
		redirect_to request.referer
	end

	private
	def book_comment_params
		params.require(:book_comment).permit(:comment)
	end
end

app/controllers/concerns/book_comments_controller.rb
class BookCommentsController < ApplicationController

	def create
		@book = Book.find(params[:book_id])
		@book_comment = BookComment.new(book_comment_params)
		@book_comment.book_id = @book.id
		@book_comment.save
  	redirect_to request.referer
	end


	def destroy
	  	@book = Book.find(params[:book_id])
	  	book_comment = @book.book_comments.find(params[:id])
			book_comment.destro
			redirect_to request.referer
	end

private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
 before_action :authenticate_user!

  def create
    book = Book.find(params[:book_id])
    favorite = book.favorites.new(user_id:current_user.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = book.favorites.find_by(user_id:current_user.id)
    favorite.destroy
    redirect_to request.referer
  end
<<<<<<< HEAD
end
=======

end
>>>>>>> 8c9886d0fc2ff2c2a3b1084824cc18a5a29ebe2f

app/views/books/index.html.erb
  <main>
  <div class="container">
   <div class="row">
   <div class="col-md-3 ">
       <% if @book.errors.any? %>
       <%= @book.errors.count %>errors prohibited this obj from being saved:
       <% @book.errors.full_messages.each do |message| %>
       <%= message %>
       <% end %>
       <% end %>
    <h1>User info</h1>
    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
<table class="table">
  <tbody>
<tr></tr>
  <tr>
 <th>name</th>
 <th><%= @user.name %></th>
  </tr>
  <tr>
 <th>introduction</th>
 <th><%= @user.introduction %></th>
  </tr>
</tbody></table>


     <%= link_to edit_user_path(@user.id) do %>
      <i class="fas fa-user-cog" ></i>
     <% end %>

    <h2>New book</h2>
    <%= form_with model: @book, local:true do |f| %>
    <p>Title</p>
     <%= f.text_field :title %>
    <p>Opinion</p>
     <%= f.text_area :body %>
    <div class="form-group">
     <%= f.submit "Create Book", class: "btn btn-success" %>
     <% end %>
    </div>
  </div>

     <div class="col-md-8 offset-md-1">
       <h2>Books</h2>
       <table class="table table-hover table-inverse">
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <% @books.each do |book| %>
          <tr>
          <td>
           <%= link_to user_path(book.user.id) do %>
           <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40 ,size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
           <% end %>
           </td>

          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
          <td>
          <% if book.favorited_by?(current_user) %>
         <%= link_to book_favorites_path(book), method: :delete do %>
         ♥<%= book.favorites.count %>
         <% end %>

         <% else %>

         <%= link_to book_favorites_path(book), method: :post do %>
         ♡<%= book.favorites.count %>
         <% end %>
          <p>コメント件数：<%= book.book_comments.count %></p>
         <% end %></td>
<% end %>
       </table>
      </div>
     </div>
    </div>
   </main>

app/views/books/new.html.erb
  <main>
  <div class="container">
   <div class="row">
   <div class="col-md-3 ">
       <% if @book.errors.any? %>
       <%= @book.errors.count %>errors prohibited this obj from being saved:
       <% @book.errors.full_messages.each do |message| %>
       <%= message %>
       <% end %>
       <% end %>
    <h1>User info</h1>
    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
<table class="table">
  <tbody>
<tr></tr>
  <tr>
 <th>name</th>
 <th><%= @user.name %>
  </tr>
  <tr>
 <th>introduction</th>
 <th><%= @user.introduction %></th>
  </tr>
</tbody></table>


     <%= link_to edit_user_path(@user.id) do %>
      <i class="fas fa-user-cog" ></i>
     <% end %>

    <h2>New book</h2>
    <%= form_with model: @book, local:true do |f| %>
    <p>Title</p>
     <%= f.text_field :title %>
    <p>Opinion</p>
     <%= f.text_area :Opinion %>
    <div class="form-group">
     <%= f.submit "Create Book", class: "btn btn-success" %>
     <% end %>
    </div>
  </div>

     <div class="col-md-8 offset-md-1">
       <h2>Books</h2>
       <table class="table table-hover table-inverse">
         <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
         </tr>
         <tr>
              <% @book.each do |book| %>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>
          <% end %>
          </tr>
       </table>
      </div>
     </div>
    </div>
   </main>

app/views/books/show.html.erb
<main>

 <div class="container">
  <div class="row">
  <div class="col-md-3">
        <% if @book.errors.any? %>
       <%= @book.errors.count %>errors prohibited this obj from being saved:
       <% @book.errors.full_messages.each do |message| %>
       <%= message %>
       <% end %>
       <% end %>
   <h2>User info</h2>
   <table>
    <thead>
     <tbody>
      <%= attachment_image_tag @users, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
      <tr></tr>
        <tr>
       <th>name</th>

        </tr>
        <tr>
       <th>introduction</th>

        </tr>
      </tbody></table>

       <%= link_to  edit_book_path(@book) do %>
      <i class="fas fa-user-cog" ></i>
     <% end %>



   <h2>New book</h2>
   <%= form_with model: @booknew, local:true do |f| %>
   <p>Title</p>
    <%= f.text_field :title %>
   <p>Opinion</p>
    <%= f.text_area :body %>
   <div class="form-group">
    <%= f.submit "Create Book", class: "btn btn-success" %>
    <% end %>
   </div>
   </div>

     <div class="col-md-8 offset-md-1">
       <h2>Book  detail</h2>
       <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
         <tbody>
          <td></td>
           <td><%= link_to user_path(@book.user) do %>
           <%= attachment_image_tag @users, :profile_image, size: "40x40", fallback:"no_image.jpg" %>
           <% end %></td>
           <td><%= link_to  %></td>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>
         <% if @book.user.id == current_user.id %>
           <div class="form-group">
           <td><%= link_to  'Edit', edit_book_path(@book), class:"btn btn-sm btn-success" %></td>
           <td><%= link_to 'Destroy', book_path(@book), method: :delete,  class:"btn btn-sm btn-danger" %></td>
         <% end %>

         #コメント
          <% @book_comments.each do |book_comment| %>
            <%= link_to 'destroy', book_book_comment_path(@book.id,book_comment.id),method: :delete,class: "btn btn-success book_comment" %>
            <%= book_comment.comment %>

          <% end %>
          </div>
           <p>
          <div class="new-comment">
          <%= form_for [@book, @book_comment] do |f| %>
            <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
            <%= f.submit "送信する" %>
          <% end %>


         </div>

         </tr>
          </tbody>
         </tr>
       </table>
      </div>
  </div>
  </div>
</main>